"""empty message

Revision ID: 04f1a87b3db2
Revises: ee9640482475
Create Date: 2016-09-21 08:41:03.696558

"""

# revision identifiers, used by Alembic.
revision = '04f1a87b3db2'
down_revision = 'ee9640482475'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['human.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    ### end Alembic commands ###
