"""empty message

Revision ID: afe9a7b15af9
Revises: ebb5d4aa1c8b
Create Date: 2016-10-30 20:41:06.460707

"""

# revision identifiers, used by Alembic.
revision = 'afe9a7b15af9'
down_revision = 'ebb5d4aa1c8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing_sms', sa.Column('send_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoing_sms', 'send_at')
    ### end Alembic commands ###
