"""empty message

Revision ID: eeeeb8bf43d6
Revises: afe9a7b15af9
Create Date: 2016-11-02 08:07:30.366276

"""

# revision identifiers, used by Alembic.
revision = 'eeeeb8bf43d6'
down_revision = 'afe9a7b15af9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing_sms', sa.Column('sent', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoing_sms', 'sent')
    ### end Alembic commands ###
